POST http://localhost:5002/user HTTP/1.1
Content-Type: application/json

{
    "firstName": "Vasya",
    "lastName": "Ivanov",
    "email": "vasya12345@mail.com",
    "login": "vasya12345",
    "password": "qwerty"
}